version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mesbouquins
    container_name: mesbouquins
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: mesbouquins
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../src/./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mesbouquins

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src/.:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mesbouquins

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mesbouquins

#Docker Networks
networks:
  mesbouquins:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local